baseURL = "https://d1nuc0m.it"
theme = "risotto"
title = "d1nuc0m's homepage"
author = "Francesco Di Nucci"
copyright = "Copyleft üÑØ 2025 Francesco Di Nucci - [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) (unless otherwise specified)"
pagination.pagerSize = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "gruvbox-dark"

# Sidebar: about/bio
[params.about]
title = "d1nuc0m"
description = "Sysadmin, student, FOSS enthusiast"
# unicode/emoji logo:
#logo = "üçö"
# or use an image:
logo_image = "images/about_image.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/d1nuc0m/"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/francesco-di-nucci"

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog/"
    weight = 10

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv/"
    weight = 10

  [[menu.main]]
    identifier = "logo"
    name = "Logo"
    url = "/logo/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[privacy]

  [privacy.vimeo]
    disabled = true
    simple = true

  [privacy.twitter]
    disabled = true
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = true
    simple = true

  [privacy.youtube]
    disabled = true
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
